# Generated by Django 3.1.12 on 2021-06-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210612_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='section',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
