# Generated by Django 3.1.12 on 2021-06-14 19:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210613_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='section',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='section',
            name='pdf_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), default=[], size=None),
        ),
        migrations.AddField(
            model_name='section',
            name='youtube_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), default=[], size=None),
        ),
    ]
