# Generated by Django 3.1.12 on 2021-06-14 19:53

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210614_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='pdf_urls',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='section',
            name='youtube_urls',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), default=[], size=None),
        ),
    ]
