# Generated by Django 3.1.12 on 2021-06-14 19:59

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_auto_20210614_1953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="pdf_urls",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.URLField(blank=True, max_length=1000),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="youtube_urls",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.URLField(blank=True, max_length=1000),
                default=list,
                size=None,
            ),
        ),
    ]
