# Generated by Django 3.1.12 on 2021-06-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
