# Generated by Django 3.1.12 on 2021-06-14 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_section_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='total',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
