# Generated by Django 3.1.12 on 2021-06-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210614_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='subtitle',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='section',
            name='subtitle',
            field=models.TextField(default=''),
        ),
    ]
