# Generated by Django 3.1.12 on 2021-06-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_auto_20210628_1830"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="image",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
