# Generated by Django 3.1.12 on 2021-06-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_section_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="subtitle",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="section",
            name="subtitle",
            field=models.TextField(blank=True, default=""),
        ),
    ]
