# Generated by Django 3.1.12 on 2021-06-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210628_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
