# Generated by Django 3.1.12 on 2021-07-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_question_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='member_plan',
            field=models.TextField(choices=[('free', 'Free Bar'), ('baby', 'Baby Bar'), ('pro', 'Pro Bar')], default='free', max_length=10),
        ),
    ]
