# Generated by Django 3.1.12 on 2021-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_level_member_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='member_plan',
            field=models.CharField(choices=[('free', 'Free Bar'), ('baby', 'Baby Bar'), ('pro', 'Pro Bar')], default='free', max_length=10),
        ),
    ]
