# Generated by Django 3.1.12 on 2021-08-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0020_auto_20210721_1545"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="level",
            name="member_plan",
        ),
        migrations.AlterField(
            model_name="result",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
