# Generated by Django 3.1.12 on 2021-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_auto_20210805_1700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        )
    ]
