# Generated by Django 3.1.12 on 2021-08-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210822_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_free',
        ),
    ]
