# Generated by Django 3.1.12 on 2021-09-04 08:10

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_remove_section_is_free"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="pdf_urls",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=1000),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="youtube_urls",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=1000),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
