# Generated by Django 3.1.12 on 2021-09-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210904_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
