# Generated by Django 3.1.12 on 2023-09-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210904_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='is_drills_and_videos',
            field=models.BooleanField(default=False),
        ),
    ]
