# Generated by Django 3.1.12 on 2024-08-17 10:23

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_level_is_drills_and_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_enable_login', models.BooleanField(default=True)),
                ('is_enable_delete_account', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
