# Generated by Django 3.1.12 on 2024-12-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
