version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cbed_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    volumes:
      - ../upload:/app/cbed/media/
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cbed_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - ./production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    ports:
      - "5555:5432"
    restart: unless-stopped

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: cbed_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped

  redis:
    image: redis:5.0
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: cbed_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: cbed_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: cbed_production_flower
    command: /start-flower
    ports:
      - "5556:5555"
