from inapppy import AppStoreValidator, InAppPyValidationError

bundle_id = 'com.barexamdrills.app'
auto_retry_wrong_env_request = False

validator = AppStoreValidator(bundle_id, auto_retry_wrong_env_request=auto_retry_wrong_env_request)

RECEIPT="MIAGCSqGSIb3DQEHAqCAMIACAQExDzANBglghkgBZQMEAgEFADCABgkqhkiG9w0BBwGggCSABIIBQTGCAT0wDwIBAAIBAQQHDAVYY29kZTALAgEBAgEBBAMCAQAwHwIBAgIBAQQXDBVjb20uYmFyZXhhbWRyaWxscy5hcHAwCwIBAwIBAQQDDAExMBACAQQCAQEECGtu+1kOAAAAMBwCAQUCAQEEFORZpV/xGsna8Shpj+3BE9GptdVJMAoCAQgCAQEEAhYAMB4CAQwCAQEEFhYUMjAyMS0wNy0xMVQwNTowNzoxNlowcwIBEQIBAQRrMWkwDAICBqUCAQEEAwIBATAqAgIGpgIBAQQhDB9jb20uYmFyZXhhbWRyaWxscy5hcHAudW5sb2NrYWxsMAwCAganAgEBBAMMATAwHwICBqgCAQEEFhYUMjAyMS0wNy0xMVQwNTowNzoxNlowHgIBFQIBAQQWFhQ0MDAxLTAxLTAxVDAwOjAwOjAwWgAAAAAAAKCCA3gwggN0MIICXKADAgECAgEBMA0GCSqGSIb3DQEBCwUAMF8xETAPBgNVBAMMCFN0b3JlS2l0MREwDwYDVQQKDAhTdG9yZUtpdDERMA8GA1UECwwIU3RvcmVLaXQxCzAJBgNVBAYTAlVTMRcwFQYJKoZIhvcNAQkBFghTdG9yZUtpdDAeFw0yMDA0MDExNzUyMzVaFw00MDAzMjcxNzUyMzVaMF8xETAPBgNVBAMMCFN0b3JlS2l0MREwDwYDVQQKDAhTdG9yZUtpdDERMA8GA1UECwwIU3RvcmVLaXQxCzAJBgNVBAYTAlVTMRcwFQYJKoZIhvcNAQkBFghTdG9yZUtpdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANt/kDwscw/blyZLk7sK+KEhPshh2STIXh91PtqT2zEakYC5v+UMyzy7DkRiJvoEKbZJ52/gG+YNaM0lbsN2CPVKC656dDzEqQuzz2IP+7S899uEXijrRw3x7Yus9Z+wCTijbnvLJlAKGuGJ0XJ2CzlMy09uwLNft5W6uahdSnSr729BpX4Jjbo9Pc1wV9jt79Xad8iTBBzvCYh4Zc6B8o1y5wcabiYS9zKxDbs4kGsGxPwN5ZVQzZHIuiX0WMmM4XHbSkXzLRmWA1aBpkTudXdbU894rF26Pl9QK1wpjN3C1yoX3yK01+R4qK+obafB2mgtZszPKQtQLOPC++ZfEsECAwEAAaM7MDkwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAoQwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwMwDQYJKoZIhvcNAQELBQADggEBALIA4Dzx6OlivcDWHUCeV7k4kHd2UtKoS3BuuGeZ+7OKVZ/vHSi4XyrRc581Rze7RtN2EPLwaezNYplx+WCKhEg4xL2LZyW5q2wzZa3Ywpp4SA/pzMEnDcbPZDxtgFkzjMo2BioRG41Jzgj/ZsBHKEvrWsErCVYspaoJA3syMdzohXhIzsDFEhFqDwyuLwXKb3pkfyAsdeZMsRLT/eMfXg19uFjXoHzkf2Orl5orwyrY0LLh1VoNORtvZyipEoPWh3htmb1eswrgmM726sOObWnrt0CBPYc9cFHRxF2Npdx/alga3mB2N1Ls/6wZXQwVL4oP9YnI1ysdHuwrkQWnPU8xggGPMIIBiwIBATBkMF8xETAPBgNVBAMMCFN0b3JlS2l0MREwDwYDVQQKDAhTdG9yZUtpdDERMA8GA1UECwwIU3RvcmVLaXQxCzAJBgNVBAYTAlVTMRcwFQYJKoZIhvcNAQkBFghTdG9yZUtpdAIBATANBglghkgBZQMEAgEFADANBgkqhkiG9w0BAQsFAASCAQCwfGdb/2uS3lcNC6lqr3BeyCNiKNIKe9dAh/PWXGOTupEqq3X7L/PVH+YsApIuAzUjdfikImc9LRgpWOoHOHHqWG6dY9LwPZ2b4lP10sfo13ceR+Y3tJv11MjZJqclsRlMa3NF0x2leZbaKs458MlGHF+2olEcfr6HYH/t37cFefQeTXS0Cu3/Ntk17410IpU835CzgGOKstwguCTQBZNv7Eph0fwjODKXIsnJeUcteeUCksGk1rrD7+JdhGPW2iD+go4w8+ZQDTtEgAKTfcgrDXMYPp63yh/SQRV3Yb8+fDek8mD1+T2AcTyo4kfUTOvyoXU0lBoYjaHu2JL7UhTPAAAAAAAA"
try:
    exclude_old_transactions = False  # if True, include only the latest renewal transaction
    validation_result = validator.validate(RECEIPT,None,
                                           exclude_old_transactions=exclude_old_transactions)
    print(validation_result)
except InAppPyValidationError as ex:
    # handle validation error
    response_from_apple = ex.raw_response  # contains actual response from AppStore service.
    print(response_from_apple)
