# Generated by Django 3.1.12 on 2021-06-12 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
