# Generated by Django 3.1.12 on 2021-06-12 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
