# Generated by Django 3.1.12 on 2021-06-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_section_is_free'),
        ('users', '0002_user_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_sections',
            field=models.ManyToManyField(to='main.Section'),
        ),
    ]
