# Generated by Django 3.1.12 on 2021-08-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_auto_20210822_1807"),
        ("users", "0008_auto_20210822_1535"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="available_sections",
        ),
        migrations.AddField(
            model_name="user",
            name="current_mbe_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.section",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_unlock_essay_pt",
            field=models.BooleanField(default=False),
        ),
    ]
