# Generated by Django 3.1.12 on 2021-08-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_section_is_free'),
        ('users', '0009_auto_20210822_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_mbe_section',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': 'MBE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.section'),
        ),
    ]
