# Generated by Django 3.1.12 on 2021-09-04 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_remove_section_is_free"),
        ("users", "0011_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="current_mbe_section",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"level__name": "MBE Level Drills"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.section",
            ),
        ),
    ]
