# Generated by Django 3.1.12 on 2023-10-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_level_is_drills_and_videos'),
        ('users', '0012_auto_20210904_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_fl_mcq_drill',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': 'FL MCQ Drills'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_fl_mcq_drill', to='main.section'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_mbe_section',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': 'MBE Level Drills'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_mbe_section', to='main.section'),
        ),
    ]
