# Generated by Django 3.1.12 on 2024-08-11 13:37

import cbed.main.consts
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_level_is_drills_and_videos'),
        ('users', '0013_auto_20231002_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_ca_mcq_drill',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': cbed.main.consts.LevelNames['CA_MCQ_DRILLS']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_ca_mcq_drill', to='main.section'),
        ),
    ]
