# Generated by Django 3.1.12 on 2024-08-19 03:35

import cbed.main.consts
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_config'),
        ('users', '0014_user_current_ca_mcq_drill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_mpre_drill',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': cbed.main.consts.LevelNames['MPRE_DRILLS']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_mpre_drill', to='main.section'),
        ),
    ]
