# Generated by Django 3.1.12 on 2024-09-17 01:37

import cbed.main.consts
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_config'),
        ('users', '0015_user_current_mpre_drill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_agency_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': cbed.main.consts.LevelNames['AGENCY_LEVEL']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_agency_level', to='main.section'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_conflicts_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': cbed.main.consts.LevelNames['CONFLICTS_LEVEL']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_conflicts_level', to='main.section'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_corps_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': cbed.main.consts.LevelNames['CORPS_LEVEL']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_corps_level', to='main.section'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_fam_law_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': cbed.main.consts.LevelNames['FAM_LAW_LEVEL']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_fam_law_level', to='main.section'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_partnerships_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': cbed.main.consts.LevelNames['PARTNERSHIPS_LEVEL']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_partnerships_level', to='main.section'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_trans_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': cbed.main.consts.LevelNames['SEC_TRANS_LEVEL']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_trans_level', to='main.section'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_trusts_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': cbed.main.consts.LevelNames['TRUSTS_LEVEL']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_trusts_level', to='main.section'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_wills_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': cbed.main.consts.LevelNames['WILLS_LEVEL']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_wills_level', to='main.section'),
        ),
    ]
