# Generated by Django 3.1.12 on 2024-09-17 01:50

import cbed.main.consts
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_config'),
        ('users', '0016_auto_20240917_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_trans_level',
        ),
        migrations.AddField(
            model_name='user',
            name='current_sec_trans_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__name': cbed.main.consts.LevelNames['SEC_TRANS_LEVEL']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sec_trans_level', to='main.section'),
        ),
    ]
