# Generated by Django 3.1.12 on 2025-06-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_is_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='essay_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mpt_count',
            field=models.IntegerField(default=0),
        ),
    ]
