# Generated by Django 3.1.12 on 2026-09-14 21:17

import cbed.main.consts
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_subscriptionplan'),
        ('users', '0026_user_current_ng_lrpt_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tutor_for_bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_mixed_mbe_section',
            field=models.ForeignKey(blank=True, db_column='current_mixed_mbe_section_id', limit_choices_to={'level__name': cbed.main.consts.LevelNames['MIXED_MBE_SETS']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_mixed_mbe_section', to='main.section'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_ng_mcq_1_choice_section',
            field=models.ForeignKey(blank=True, db_column='current_ng_mcq_1_choice_section_id', limit_choices_to={'level__name': cbed.main.consts.LevelNames['NG_MCQ_1_CHOICE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_ng_mcq_1_choice_section', to='main.section'),
        ),
    ]
