# Generated by Django 3.1.12 on 2021-07-27 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product', models.CharField(choices=[('com.barexamdrills.app.babybarjune', 'Baby Bar June'), ('com.barexamdrills.app.babybaroct', 'Baby Bar Oct'), ('com.barexamdrills.app.probarfeb', 'Pro Bar Feb'), ('com.barexamdrills.app.probarjuly', 'Pro Bar July'), ('com.barexamdrills.app.unlockall', 'Test'), ('free', 'Free')], max_length=128)),
                ('ref', models.CharField(max_length=512, unique=True)),
                ('info', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
