# Generated by Django 3.1.12 on 2025-06-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_appstorerawtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
